# Generated by Django 4.1 on 2024-05-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("surname", models.CharField(max_length=10)),
                ("mail", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=12)),
                ("photo", models.ImageField(upload_to="images")),
                ("text", models.CharField(max_length=150)),
                ("industry", models.ManyToManyField(to="www.industry")),
            ],
        ),
    ]
