# Generated by Django 4.1 on 2024-05-17 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0003_remove_acceptedoffer_accepted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acceptedoffer",
            name="industry",
        ),
    ]
