# Generated by Django 4.1 on 2024-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0004_remove_acceptedoffer_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptedoffer",
            name="industry",
            field=models.ManyToManyField(to="www.industry"),
        ),
    ]
