# Generated by Django 4.1 on 2024-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0007_opinion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opinion",
            old_name="offer",
            new_name="accepted_offer",
        ),
        migrations.AlterField(
            model_name="opinion",
            name="author",
            field=models.CharField(max_length=100),
        ),
    ]
