# Generated by Django 4.1 on 2024-05-18 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0009_like_unlike_delete_opinion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="comment",
            new_name="acceptedoffer",
        ),
        migrations.RenameField(
            model_name="unlike",
            old_name="comment",
            new_name="acceptedoffer",
        ),
    ]
