# Generated by Django 4.1 on 2024-05-18 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0011_rename_acceptedoffer_like_accepted_offer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="accepted_offer",
            new_name="accept_offer",
        ),
        migrations.RenameField(
            model_name="unlike",
            old_name="accepted_offer",
            new_name="accept_offer",
        ),
    ]
